development:
  KEY:  '\x0F\x0E\xB4\x18\xD3\x82\xC0\xDC\x1Aqg\xBA\xFB\x86\xBC\xD3,8\x88\x14\x99\x10\xE0\xCE\x854\xD0\xA7\x86\xF1\xA9\x06\xB2\x85\xA7\xFB\x14y-,\x06%\x92\x99\xD1\xB2\x14D\\fZ\xA5i\xE'
  SALT: 'F\x1D\xB5\b?M\xF5v\xE3\x86\xE2\xDEh\xE2+\xCEx'\x01V\x9DT\xBF\xE9}\xB9\x0E\xBB\xBE\x9C\xA5\xCC\xEE\fVF\xC4w\xAF\x88\xE0\x15\xC8\xEF\xF7\x9D\xB0\xD3\xCB\xEBI\x17\xAF-\xF8Y\xF4\'
  
